name: Feature Request
description: Suggest a feature for the project!
title: '[Feature]:'
labels: 
  - enhancement
assignees:
  - ApplePieAngel
body:
  - type: textarea
    attributes:
      label: Describe the feature you'd like!

